#!/bin/sh

set_applet()
{
    template_path="/usr/share/meegotouch/applicationextensions/statusindicatormenu-${1}.desktop"
    template_data="[Desktop Entry]\nType=X-MeeGoApplicationExtension\nName=Status Indicator Menu Applet\n\n[X-MeeGoApplicationExtension]\nInterface=com.meego.core.MStatusIndicatorMenuExtensionInterface/1.0\nExtension=libstatusindicatormenu-${2}.so"
    echo -e $template_data > $template_path
}

remove_applet()
{
    if [ -f /usr/share/meegotouch/applicationextensions/statusindicatormenu-${1}.desktop ]; then
        rm -f /usr/share/meegotouch/applicationextensions/statusindicatormenu-${1}.desktop
    fi
}

set -e

gconftool -s -t str /apps/status-menu-extensions/preinst $1

if [ "$1" == "install" ]; then
    echo "Pre-installation script install ..."

    set_applet internetconnection call
    set_applet bluetooth internetconnection
    remove_applet presence
fi

if (pidof extensions_daemon > /dev/null); then
    killall extensions_daemon
fi

if [ -n "`initctl status xsession/sysuid | grep running`" ]
then
    /sbin/initctl stop xsession/sysuid
fi

exit 0
